# Siven Sadiyan's Docker Configuration for OpenCart 3 (https://github.com/siven76/docker-opencart)
# Version 1.0.0

version: "3"

services:
  app:
    image: siven76/opencart-nginx:1.13
    ports:
      - 80:8000
    links:
      - db
      - phpfpm
    volumes: &appvolumes
      - ./src:/var/www/html:delegated
      - ~/.composer:/var/www/html/var/composer_home:delegated
      - ~/.composer:/var/www/.composer:delegated
      - appdata:/sock
      - appdata:/var/www/html/vendor

  phpfpm:
    image: siven76/opencart-php:7.1-fpm
    links:
      - db
    volumes: *appvolumes

  db:
    image: percona:5.7
    ports:
      - 3306:3306
    env_file: env/db.env
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  appdata:
  dbdata: